import Head from "next/head";
import Image from "next/image";
import { NextPage } from "next";
import { Container } from "@mui/material";
import { useAuth } from "../hooks/useAuth";

const HomePage: NextPage = () => {
  const isAuth = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        {isAuth ? <div>Is Logged</div> : <div>Is not Logged</div>}
      </Container>
    </>
  );
};

export default HomePage;
