import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import { Container } from "@mui/material";

const HomePage: NextPage = () => {
  const isAuth = false;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        {isAuth ? <div>Is Logged</div> : <div>Is not Logged</div>}
      </Container>
    </>
  );
};

export default HomePage;
