version: '3.1'

services:
  mosquitto:
    restart: "no"
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/config
  database:
    image: 'postgres:latest'
    # Syntax is [port we want on our machine]:[port to retrieve in the container]
    ports:
      - 5432:5432
    # Syntax is [path on our machine]:[folder path to retrieve in the container]
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: "no"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - database
    restart: "no"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
